
name: Build Java Project

on:
  push:
    branches: [ master ]  # أو main إذا كنت تستخدم هذا الفرع
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Give permissions to gradlew
      run: chmod +x ServerX/gradlew

    - name: Build with Gradle
      run: cd ServerX && ./gradlew build

    - name: Upload build outputs
      uses: actions/upload-artifact@v4
      with:
        name: compiled-output
        path: ServerX/build/libs/
